server:
  port: ${PORT}
  servlet:
    context-path: ${CONTEXT_PATH}
applications:
  env: ${PROFILE_ENV}

spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${MYSQL_URL}
    driverClassName: ${MYSQL_DRIVER_CLASSNAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      properties:
        max:
          poll:
            interval:
              ms: 7200000
        allow:
          auto:
            create:
              topics: false
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: ${MAIL_PORT}
          auth: true
          starttls:
            enable: true
            required: true

email:
  client-url: ${CLIENT_URL}

firebase:
  credential: ${FIREBASE_CREDENTIAL_PATH}